version: "3"
services:
  tendis:
    image: vuthaihoc/tendis
    ports:
     - 51002:51002
    volumes:
     - ./tendis_data:/tendis_data
     - ./scripts/start.sh:/tendis/scripts/start.sh
     - ./scripts/tendisplus.conf:/tendis/scripts/tendisplus.conf
    restart: always